:doctype: article

= goiter

Implementation of iterator pattern based on an iterating function -
a function that accepts no arguments and returns (next item, true if next item exists).

When the bool result is false, the next item result is invalid in the sense it must be ignored for correct iteration.
These functions may be designed so that once exhausted, they continue to return (invalid value, false).

== Provided iterating functions

* ArraySliceIterFunc: iterates any type of array or slice non-recursively. Panics if value passed does not wrap an array or slice.
* IterablesFunc: iterates any number of Iterable
* MapIterFunc: iterates any kind of map non-recursively, where next item is a KeyValue{Key interface{}, Value interface{}} instance. Panics if value passed does not wrap a map.
* NoValueIterFunc: iterates nothing, always returns (nil, false)
* SingleValueIterFunc: iterates a single value, where first call to next returns (value, true), further calls return (nil, false). Array/slice/map values are just returned as one value.
* ElementsIterFunc: iterates the elements of a value, using each of the above funcs as appropriate.

== Iter struct

The Iter struct uses an iterating function to implement the iterator pattern in an idiomatic Go fashion, with some extra utility methods:

* Next is used to advance the iterator
** returns true if there is another item
** returns false if the iterating function has just been exhausted
** panics if the last call to Next exhausted the iterating function
* Value returns the value iterated by last call to Next
** panics if called after Next has exhausted the iterating function
** panics if Next has not been called since last call to Value
* SplitIntoRows splits the items into slices of at most n columns
** panics if n == 0
** panics if called after Next has exhausted the iterating function
** returns a two dimensional slice of slices
** if the iter is empty, returns an allocated empty slice of slices
* SplitIntoColumns splits the items into slices of at most n rows
** panics if n == 0
** panics if called after Next has exhausted the iterating function
** returns a two dimensional slice of slices
** if the iter is empty, returns an allocated empty slice of slices
* ToSlice collects all the items into a single slice
** panics if called after Next has exhausted the iterating function
** if the iter is empty, returns an allocated empty slice

== Constructors

* NewIter accepts an iterating function
* Of accepts a single item which is iterated using an ArraySliceIterFunc
* OfElements accepts a single item which is iterated using an ElementsIterFunc
* OfIterables accepts a vararg of Iterable which is iterated using an IterablesFunc

Since an *Iter is an Iterable, both OfElements and OfIterables can iterate the values of an *Iter,
the difference being that OfElements will only iterate one,
while OfIterables iterates any number of them.

== Examples (taken from unit tests)

=== Of constructor
....
    iter = Of(5, []int{6, 7})

    next = iter.Next()
    assert.True(t, next)
    assert.Equal(t, 5, iter.Value())

    next = iter.Next()
    assert.True(t, next)
    assert.Equal(t, []int{6, 7}, iter.Value())

    next = iter.Next()
    assert.False(t, next)

    func() {
        defer func() {
            assert.Equal(t, "Iter.Next called on exhausted iterator", recover())
        }()

        iter.Next()
        assert.Fail(t, "Must panic")
    }()
....

=== OfElements constructor
....
    iter := OfElements([]int{5, 6})

    next := iter.Next()
    assert.True(t, next)
    assert.Equal(t, 5, iter.Value())

    next = iter.Next()
    assert.True(t, next)
    assert.Equal(t, 6, iter.Value())

    next = iter.Next()
    assert.False(t, next)

    func() {
        defer func() {
            assert.Equal(t, "Iter.Next called on exhausted iterator", recover())
        }()

        iter.Next()
        assert.Fail(t, "Must panic")
    }()
....

=== For loop
....
    var (
        iter     = Of(5, []int{6, 7})
        idx      = 0
        expected = []interface{}{5, []int{6, 7}}
    )

    for iter.Next() {
        assert.Equal(t, expected[idx], iter.Value())
        idx++
    }

    assert.Equal(t, 2, idx)

    func() {
        defer func() {
            assert.Equal(t, "Iter.Next called on exhausted iterator", recover())
        }()

        iter.Next()
        assert.Fail(t, "Must panic")
    }()
....
